// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/contact-variants/ConversationalWizard.tsx": () => import("../components/mockups/contact-variants/ConversationalWizard.tsx"),
  "./components/mockups/contact-variants/InlineMadLibs.tsx": () => import("../components/mockups/contact-variants/InlineMadLibs.tsx"),
  "./components/mockups/contact-variants/RateEstimatorLed.tsx": () => import("../components/mockups/contact-variants/RateEstimatorLed.tsx"),
  "./components/mockups/contact-variants/SplitMapImmersive.tsx": () => import("../components/mockups/contact-variants/SplitMapImmersive.tsx"),
  "./components/mockups/homepage-variants/CorridorMap.tsx": () => import("../components/mockups/homepage-variants/CorridorMap.tsx"),
  "./components/mockups/homepage-variants/QuoteFirst.tsx": () => import("../components/mockups/homepage-variants/QuoteFirst.tsx"),
  "./components/mockups/homepage-variants/ServiceNavigator.tsx": () => import("../components/mockups/homepage-variants/ServiceNavigator.tsx"),
  "./components/mockups/homepage-variants/TrustFirst.tsx": () => import("../components/mockups/homepage-variants/TrustFirst.tsx")
};
